### ISSUE TITLE
Move RSSNotifier to this repo and add role mentions support

### ISSUE THREAD

**Issue by Jackenmen** [jack1142/JackCogs#34]
See: https://github.com/aikaterna/aikaterna-cogs/issues/155

**Comment by Jackenmen** [comment]
resolved by https://github.com/jack1142/JackCogs/commit/d5b6982372502469fe48569c7189cc9578c4f3e9

**Comment by owocado** [comment]
Holy shit it was fast. thank you. 💯 ❤️
