### ISSUE TITLE
last update broke rssnotifier

### ISSUE THREAD

**Issue by owocado** [jack1142/JackCogs#37]
Hi,
the recent update to rssnotifier cog is broken. As soon as I updated the cog, the minute after, it pinged the roles which were subscribed for all rss feeds added in 2 servers even when there were no updates to feeds. 
![Screenshot_20201014-011824_Discord](https://user-images.githubusercontent.com/24418520/95943604-ed11f580-0e03-11eb-86f3-10278049df9e.png)
![Screenshot_20201014-011853_Discord](https://user-images.githubusercontent.com/24418520/95943608-ee432280-0e03-11eb-8cab-72af2762e560.png)
![Screenshot_20201014-012404_Discord](https://user-images.githubusercontent.com/24418520/95943668-12066880-0e04-11eb-954d-6d19ffc2a57b.png)

**Comment by Jackenmen** [comment]
Fixed by https://github.com/aikaterna/aikaterna-cogs/pull/173
Upgrading and reloading RSS cog will make this work properly again.

**Comment by owocado** [comment]
thanks ♥️
