### ISSUE TITLE
[mee6rank] Embed colour

### ISSUE THREAD

**Issue by Merp-Me** [jack1142/JackCogs#45]
Not a necessary change but thought it would cleaner to set the embed colour to what the bots default embed colour is rather than being black.

**Comment by Jackenmen** [comment]
I went for a bit different idea and decided that I want this embed to use the same color that is used for the XP bar in `[p]mee6rankimage`.
Here's an example of how it looks now:
![image](https://user-images.githubusercontent.com/6032823/114604039-c2143b80-9c98-11eb-802f-712d27f07c99.png)

**Comment by Merp-Me** [comment]
Oh I see. Makes sense. The server has mee6 premium so we have a custom card set up which has orange by default so that's why. Thanks :)
<img width="478" alt="image" src="https://user-images.githubusercontent.com/64408204/114604416-c2a8d400-9c90-11eb-8b7b-35e846e35e3d.png">
